twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    globals:
        categoryrepository: '@App\Repository\CategoryRepository'
        Productrepository: '@App\Repository\ProductRepository'
        cartItem: '@App\cart\CartService'
        StripeService: '@App\Stripe\StripeService'
when@test:
    twig:
        strict_variables: true
